add example optimize coupling scheme parameter
joergbuchwald/ogs6py pull request #40
Opened 2022-01-18 14:49 UTC by dominik-kern

The staggered scheme of OGS (currently implemented for the HM-process) comes with a coupling parameter, whose optimal value is a-priori unknown (it depends on sources and boundaries but only negligible on the mesh).
This example demonstrates how to find this optimum iteratively.
It saves time to find the optimal value of the coupling parameter on a coarse mesh and then use it on finer meshes.

2022-02-08 09:16 UTC, dominik-kern commented
Something I may do to speedup the pull-request?

2022-02-08 21:44 UTC, joergbuchwald requested changes
I have the fear that tools like this one oxidize in their folder without people noticing them.
Therefore, I think it should be part at least of the sphinx doc (https://joergbuchwald.github.io/ogs6py-doc/), i.e. it needs doc strings, and perhaps it should be mentioned or described in the README as well.

2022-02-08 21:44 UTC, joergbuchwald commented on examples/optimize_coupling_scheme_parameter/search_toolbox.py
> +        self.model.replace_text("results_" + basename, xpath="./time_loop/output/prefix")
Can you remove all trailing white spaces?

2022-02-08 21:44 UTC, joergbuchwald commented on examples/optimize_coupling_scheme_parameter/search_toolbox.py
> +            #print(df_error.info())
I think you should remove the prints

2022-02-08 21:44 UTC, joergbuchwald commented on examples/optimize_coupling_scheme_parameter/search_toolbox.py
> +    def __init__(self, basename, ogs_dir=None):
I think you should add doc strings based on the style used in ogs.py such that it can be interpreted by sphinx.

2022-02-09 07:22 UTC, dominik-kern reviewed
I agree, commits follow.

2022-02-12 23:26 UTC, joergbuchwald approved these changes

2022-02-12 23:27 UTC, merged